# Generated by Django 5.2.7 on 2025-10-29 14:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('rpg', 'RPG'), ('action', 'Action'), ('aventure', 'Aventure'), ('strategie', 'Stratégie'), ('horror', 'Horreur'), ('sci-fi', 'Science-Fiction'), ('fantasy', 'Fantasy'), ('cyberpunk', 'Cyberpunk')], max_length=50)),
                ('ambiance', models.CharField(choices=[('sombre', 'Sombre'), ('joyeux', 'Joyeux'), ('mysterieux', 'Mystérieux'), ('epique', 'Épique'), ('humoristique', 'Humoristique')], max_length=50)),
                ('mots_cles', models.TextField(blank=True, help_text='Mots-clés séparés par des virgules')),
                ('references', models.TextField(blank=True, help_text='Références culturelles')),
                ('est_public', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes_count', models.IntegerField(default=0)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ConceptArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='concept_arts/')),
                ('description', models.TextField()),
                ('type_art', models.CharField(choices=[('character', 'Personnage'), ('environment', 'Environnement'), ('item', 'Objet'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_arts', to='games.game')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('classe', models.CharField(blank=True, choices=[('guerrier', 'Guerrier'), ('mage', 'Mage'), ('voleur', 'Voleur'), ('archer', 'Archer'), ('healer', 'Soigneur'), ('tank', 'Tank'), ('support', 'Support')], max_length=50)),
                ('role', models.CharField(choices=[('heros', 'Héros Principal'), ('antagoniste', 'Antagoniste'), ('allie', 'Allié'), ('mentor', 'Mentor'), ('neutre', 'Neutre')], max_length=50)),
                ('background', models.TextField()),
                ('gameplay_description', models.TextField(blank=True, help_text='Description du gameplay pour ce personnage')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generations_today', models.IntegerField(default=0)),
                ('daily_count', models.IntegerField(default=0)),
                ('last_reset', models.DateField(default=django.utils.timezone.now)),
                ('max_daily', models.IntegerField(default=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generation_limit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acte_1', models.TextField(help_text='Introduction et mise en place')),
                ('acte_2', models.TextField(help_text='Développement et complications')),
                ('acte_3', models.TextField(help_text='Climax et résolution')),
                ('twist', models.TextField(blank=True, help_text='Plot twist optionnel')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scenario', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('style_graphique', models.CharField(choices=[('realiste', 'Réaliste'), ('cartoon', 'Cartoon'), ('pixel_art', 'Pixel Art'), ('anime', 'Anime'), ('low_poly', 'Low Poly')], default='realiste', max_length=50)),
                ('type_monde', models.CharField(choices=[('open_world', 'Open World'), ('lineaire', 'Linéaire'), ('hub', 'Hub Central'), ('arene', 'Arène')], default='open_world', max_length=50)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='universe', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='games.game')),
            ],
            options={
                'ordering': ['-date_added'],
                'unique_together': {('user', 'game')},
            },
        ),
    ]
