# Generated by Django 5.2.7 on 2025-10-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationlimit',
            name='max_daily',
            field=models.IntegerField(default=20),
        ),
    ]
