# Generated by Django 5.2.7 on 2025-10-29 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_generationlimit_max_daily'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generationlimit',
            name='max_daily',
        ),
        migrations.AlterField(
            model_name='generationlimit',
            name='daily_count',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='generationlimit',
            name='last_reset',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='generationlimit',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
